version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server
    expose:
      - 5432
    ports:
      - 5434:5432
  nats:
    image: nats:ubuntu-latest
    expose:
      - 4222
    ports:
      - 4223:4222
  redis:
    image: redis
    expose:
      - 6379
  minio:
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9001:9000
  worker-svc:
    image: //tunggu
    command:
      - service 
      - "--" 
      - task
    depends_on:
      - postgres
      - minio
      - nats
      - redis
    environment:
      server_database__password: postgres
      server_database__database: server
      server_minio__accessKey: minioadmin
      server_minio__secretKey: minioadmin
      server_server__port__task: 7002
      server_server__port__worker: 7001
      server_server__port__performance: 7003
    ports:
      - 7001:7001
  task-svc:
    image: //tunggu
    command:
      - worker
    depends_on:
      - postgres
      - minio
      - nats
      - redis
      - worker-svc
    environment:
      server_database__password: postgres
      server_database__database: server
      server_minio__accessKey: minioadmin
      server_minio__secretKey: minioadmin
      server_server__port__task: 7002
      server_server__port__worker: 7001
      server_server__port__performance: 7003
    ports:
      - 7002:7002
  performance-svc:
    image: //tunggu
    command:
      - performance
    depends_on:
      - postgres
      - minio
      - nats
      - redis
    environment:
      server_database__password: postgres
      server_database__database: server
      server_minio__accessKey: minioadmin
      server_minio__secretKey: minioadmin
      server_server__port__task: 7002
      server_server__port__worker: 7001
      server_server__port__performance: 7003
    ports:
      - 7003:7003
